language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo sed -i 's/#START=yes/START=yes/' /etc/default/beanstalkd
  - sudo service beanstalkd start
