language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx

before_install:
  - curl -L https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.9/
  - make
  - ./beanstalkd &
  - ./beanstalkd -p 11301 &
  - cd $TRAVIS_BUILD_DIR

env:
  - BEANSTALK_ADDRESSES='beanstalk://localhost:11300,beanstalk://localhost:11301'

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
